services:
  stardog:
    image: "stardog/stardog"
    container_name: stardog-service
    ports:
      - "5820:5820"
    volumes:
      - ${LICENSE_PATH}:/var/opt/stardog

  ontorec:
    image: "registry.gitlab.cc-asp.fraunhofer.de/ontotrans/ontotranscorecomponents/ontorec:latest"
    container_name: ontorec-service
    depends_on:
      - stardog
    ports:
      - "80:80"
    