services:
  stardog:
    image: "stardog/stardog"
    container_name: stardog-compose
    ports:
      - "5820:5820"
    volumes:
      - C:\Users\Alessandro\Desktop\Universita\Ricerca\OntoTrans\stardog-home:/var/opt/stardog

  # DEVELOPMENT
  ontotranscore-api:
    image: "ontotrans/fastservice-development:latest"
    volumes:
      - C:\Users\Alessandro\Desktop\Universita\Ricerca\OntoTrans\ontotranscorecomponents\FastAPI:/app
    container_name: otcore-api
    depends_on:
       - stardog
    ports:
      - "8080:8080"

  # PRODUCTION
  # ontotranscore-api:
  #   image: "registry.gitlab.cc-asp.fraunhofer.de/ontotrans/ontotranscorecomponents/fastapi"
  #   container_name: otcore-api
  #   depends_on:
  #      - stardog
  #   ports:
  #     - "80:80"
    