services:
  ontokb:
    image: "stardog/stardog"
    container_name: stardog-service
    ports:
      - "5820:5820"
    volumes:
      - ${LICENSE_PATH}:/var/opt/stardog

  ontorec:
    image: "registry.gitlab.cc-asp.fraunhofer.de/ontotrans/ontotranscorecomponents/ontorec:pgbs"
    container_name: ontorec-service
    depends_on:
      - ontokb
    ports:
      - "80:80"
    environment:
      ONTOKB_BACKEND: stardog
      ONTOKB_HOST: ontokb
      ONTOKB_PORT: 5820
    